F_GT      = "ground_truth"
F_PRED    = "predictions"
F_LABEL   = "labels"
F_SCORES  = "scores"
F_BOXES   = "boxes"
F_GTL     = "ground_truth.label"
F_CPU     ="cpu"
ds_path = "gdrive/MyDrive/data/coco-17/"
